# Generated by Django 3.1.5 on 2021-01-28 10:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2, verbose_name='Your country'),
        ),
    ]
